language: node_js

node_js:
  - 8.9.0

sudo: required

dist: trusty

cache:
  yarn: true

notifications:
  slack: tlmader:TCHb5sywLfnNrFRdTvmfdYTQ

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn global add @angular/cli
  - yarn install

script:
  - yarn run build:prod
